name: Docker Image CI

on:
  push:
    branches: [ "arm" ]
  pull_request:
    branches: [ "arm" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:      
      DOCKER_IMAGE: arm32v7/debian:stable      
      DOCKER_TARGET_PLATFORM: linux/arm/v7    

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
